// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3_UfVAHCZI1U3qvmSqms7XIwZ-rRr_5c',
    appId: '1:802775884670:web:07da8e223fa98dfaf3892f',
    messagingSenderId: '802775884670',
    projectId: 'my-vault-vvk',
    authDomain: 'my-vault-vvk.firebaseapp.com',
    storageBucket: 'my-vault-vvk.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrhgjDGf7wvX4QE-bbGXBuNgn118aX8Qk',
    appId: '1:802775884670:android:7893339a0b13b454f3892f',
    messagingSenderId: '802775884670',
    projectId: 'my-vault-vvk',
    storageBucket: 'my-vault-vvk.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB81oVBQdFCfdi48M8VTpVM6tKPUj5k4tQ',
    appId: '1:802775884670:ios:b94e08128919f33ef3892f',
    messagingSenderId: '802775884670',
    projectId: 'my-vault-vvk',
    storageBucket: 'my-vault-vvk.firebasestorage.app',
    iosBundleId: 'com.example.myVault',
  );
}
